{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Release.Name }}
  name: {{ include "z4.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "z4.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
{{- end }}
