apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "z4.fullname" . }}
  labels:
    {{- include "z4.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "z4.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "z4.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "z4.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6355
              name: grpc
            - containerPort: 6356
              name: raft
            - containerPort: 2112
              name: metrics
          volumeMounts:
            - name: z4-data
              mountPath: /var/lib/z4
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: Z4_DB_DATA_DIR
              value: /var/lib/z4/db
            - name: Z4_PEER_DATA_DIR
              value: /var/lib/z4/cluster
            - name: Z4_PEER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Needs to match the name given to the Service object.
            - name: SERVICE_NAME
              value: {{ include "z4.fullname" . }}
            - name: Z4_PEER_ADVERTISE_ADDR
              value: "$(Z4_PEER_ID).$(SERVICE_NAME).$(POD_NAMESPACE).svc.cluster.local:6356"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: z4-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.class }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
