{
 "title": "z4",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Created",
   "type": "timeseries",
   "description": "Tasks created per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(z4_create_task_request_total[2m])) by (pod)"
    }
   ]
  },
  {
   "title": "Tasks Streamed",
   "type": "timeseries",
   "description": "Tasks sent to consumers per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(z4_streamed_task_total[2m])) by (pod)"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Leader",
   "type": "stat",
   "description": "The pod that is the cluster leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "z4_is_leader == 1", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "The number of peers in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_name=\"z4\"})"
    }
   ]
  },
  {
   "title": "Logs Received",
   "type": "timeseries",
   "description": "Number of Raft logs received per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(z4_received_log_count[2m])) by (pod)"
    }
   ]
  },
  {
   "title": "Logs Applied",
   "type": "timeseries",
   "description": "Number of Raft logs successfully applied per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(z4_applied_log_count[2m])) by (pod)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last GC Time",
   "type": "stat",
   "description": "The last time a database garbage collection ran",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "z4_last_db_gc * 1000", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Last Snapshot",
   "type": "stat",
   "description": "The last time a snapshot of the database was taken.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "z4_last_fsm_snapshot * 1000", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}