services:
  peer1:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      Z4_PEER_ID: peer1
      Z4_PEER_ADVERTISE_ADDR: peer1:6356
      Z4_DB_DATA_DIR: /var/lib/z4/db
      Z4_PEER_DATA_DIR: /var/lib/z4/cluster
      Z4_BOOTSTRAP_CLUSTER: true
    ports:
      - 6355:6355
    volumes:
      - peer1_data:/var/lib/z4
  peer2:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      Z4_PEER_ID: peer2
      Z4_PEER_ADVERTISE_ADDR: peer2:6356
      Z4_DB_DATA_DIR: /var/lib/z4/db
      Z4_PEER_DATA_DIR: /var/lib/z4/cluster
    ports:
      - 6455:6355
    volumes:
      - peer2_data:/var/lib/z4
  peer3:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      Z4_PEER_ID: peer3
      Z4_PEER_ADVERTISE_ADDR: peer3:6356
      Z4_DB_DATA_DIR: /var/lib/z4/db
      Z4_PEER_DATA_DIR: /var/lib/z4/cluster
    ports:
      - 6555:6355
    volumes:
      - peer3_data:/var/lib/z4

volumes:
  peer1_data:
  peer2_data:
  peer3_data:
