publisher:
  enabled: true
  replicas: 1

consumer:
  enabled: true
  replicas: 1

publisherImage:
  repository: mlposey/z4-load-publisher
  pullPolicy: Always
  tag: "latest"

consumerImage:
  repository: mlposey/z4-load-consumer
  pullPolicy: Always
  tag: "latest"

env:
  target: "z4-2.z4.z4.svc.cluster.local:6355"
  namespace: "load_test"
  rps: "5000"

nodeSelector:
  pool: load-test

tolerations:
  - key: load-test-node
    operator: Exists
    effect: NoSchedule

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - load-test
        topologyKey: kubernetes.io/hostname
