apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "load-test.fullname" . }}-publisher
  labels:
    {{- include "load-test.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.publisherImage.repository }}:{{ .Values.publisherImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.publisherImage.pullPolicy }}
          env:
            - name: TARGET
              value: {{ .Values.env.target }}
            - name: NAMESPACE
              value: {{ .Values.env.namespace }}
            - name: RPS
              value: "{{ .Values.env.rps }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "load-test.fullname" . }}-consumer
  labels:
    {{- include "load-test.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.consumerImage.repository }}:{{ .Values.consumerImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.consumerImage.pullPolicy }}
          env:
            - name: TARGET
              value: {{ .Values.env.target }}
            - name: NAMESPACE
              value: {{ .Values.env.namespace }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 4